version: "3.7"
services:
  yt-downloader-client:
    container_name: ytDownloaderClient
    build: ./
    image: yt-downloader-client
    ports:
      - 4000:3000
    depends_on:
      - yt-downloader-daemon
  yt-downloader-daemon:
    container_name: ytDownloaderDaemon
    build: ./daemon
    image: yt-downloader-daemon
    volumes:
      - ./data:/data
